---
title: "Penguine_package"
author: "Sally Heo"
date: "3/3/2022"
output: 
  html_document:
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = '../Outputs/', warning = FALSE, message = FALSE) # go up a level, then click on output
```

# Load the libraries
```{r}
library(kableExtra) # Load KableExtra 
library(tidyverse) # Load tidyverse
library(here) # Load here
library(palmerpenguins) #Load Palmer Penguins

```

install.packages("kableExtra")
install.packages("y)

# Inspect the data
```{r}
glimpse(penguins)
```
# Plot
```{r penguin1, fig.width=3, fig.height=4, fig.asp=1.2, fig.align='center', fig.cap="This is a plot of penguins", echo=FALSE}
penguins %>% # Using penguin dataset # Penguin data frame
  ggplot(aes(x = bill_length_mm,# Length
             y = bill_depth_mm,#depth 
             color = species))+ #color with species
  geom_point()
```

```{r}
penguins %>% 
  group_by(species) %>% 
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>% 
  kbl() %>% # make it a kable table
  kable_classic() %>% 
  row_spec(2, bold = T, color = "white", background = "red") %>% 
  kable_styling(full_width = FALSE)
# What are the specs for each row

```


